/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rebsea_jalint_jni_Jalint */

#ifndef _Included_com_rebsea_jalint_jni_Jalint
#define _Included_com_rebsea_jalint_jni_Jalint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rebsea_jalint_jni_Jalint
 * Method:    simpleExample_flintPow2
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rebsea_jalint_jni_Jalint_simpleExample_1flintPow2
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
